Improve Ref Docs
adafruit/Adafruit_CircuitPython_LIS3DH pull request #25
Opened 2018-02-28 06:21 UTC by sommersoft

[Per Issue #566](https://github.com/adafruit/circuitpython/issues/566)

Didn't rename any of the examples on this one. Felt it better to leave them all separated, although the case could be made to consider `accel.py` as the simpletest.

If any examples are renamed, this Learn Guide will need to be updated:
https://learn.adafruit.com/circuitpython-hardware-lis3dh-accelerometer?view=all#software

2018-02-28 18:54 UTC, kattni requested changes
Great job! I suggested one change in-line. I agree that `accel.py` should be renamed to the appropriate simpletest. Please make these changes and this should be good to go!

2018-02-28 18:54 UTC, kattni commented on adafruit_lis3dh.py
> +        Set the tap detection parameters.
Change to `The tap detection parameters.`

2018-03-01 02:06 UTC, sommersoft commented
Updates made. Learn Guide will need to be changed.

2018-03-01 23:47 UTC, kattni approved these changes
Looks great, thanks!

2018-03-01 23:47 UTC, merged

2018-03-02 00:02 UTC, kattni commented
Guide updated.